name: Deploy to Render

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: bundle install
      
    - name: Deploy to Render
      uses: render-examples/action-deploy-render@main
      env:
        RENDER_API_KEY: ${{ secrets.RENDER }}