name: Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Deploy to Render
        run: |
            curl -X GET "https://api.render.com/deploy/srv-ckudhubamefc73fosi40?key=SM6_ZVhMb14"



          # curl -X POST "https://api.render.com/v1/deploys" \
          # -H "Authorization: Bearer ${{ secrets.RENDER }}" \
          # -d "branch=master" \
          # -d "directory=."